name: Build

on:
  workflow_dispatch:
    inputs:
      docker_hub_registry:
        type: string
        description: DockerHub registry
        # required: true
        default: docker.io
      docker_hub_organization:
        type: string
        description: DockerHub organization
        # required: true
        default: mahendrapaipuri
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# defaults:
#   run:
#     shell: bash -l {0}

jobs:
  docker:
    uses: ./.github/workflows/step_docker.yml
    with:
      registry: ${{ inputs.docker_hub_registry || 'docker.io' }}
      organization: ${{ inputs.docker_hub_organization || 'mahendrapaipuri' }}
    secrets:  
      login: ${{ secrets.DOCKER_HUB_LOGIN }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       # extension:
  #       #   - logout
  #       #   - theme-toggler
  #       #   - topbar-text
  #       include:
  #         - extension: logout
  #           name: logout
  #         - extension: theme-toggler
  #           name: theme_toggler
  #         - extension: topbar-text
  #           name: topbar_text

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Test matrix variables
  #       run: |
  #         set -eux

  #         echo "${{ matrix.name }}"
  #         echo "${{ matrix.extension }}"
