name: docker
run-name: Docker images

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: Registry
        required: true
      organization:
        type: string
        description: Organization
        required: true
    secrets:
      login:
        required: true
      password:
        required: true

jobs:
  images:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tags
        run: git fetch --tags origin

      - name: Check tags
        run: git tag --sort=committerdate

      - name: Install chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          which google-chrome

      - name: Get target branch
        id: target_branch
        run: |
          which clang
          command -v clang
          clang --version
          echo $PATH
          clang -v 2>&1 | grep version | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+"
          chmod +x install_clang.sh
          ./install_clang.sh
          echo "Second"
          ./install_clang.sh
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "name=$(echo $GITHUB_BASE_REF)" >> $GITHUB_OUTPUT
          else
            echo "name=nightly" >> $GITHUB_OUTPUT
          fi
          which clang
          which llc

      - name: Print vars
        run: |
            echo "${{ steps.target_branch.outputs.name }}"
            echo "${{ inputs.registry }}/${{ inputs.organization }}"
            echo "${{ secrets.password }}"
            echo "${{ secrets.login }}"
